/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CareAssessmentRouteImport } from './routes/care-assessment'
import { Route as FollowUpsRouteImport } from './routes/follow-ups'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MyCareRouteImport } from './routes/my-care'
import { Route as PatientLoginRouteImport } from './routes/patient-login'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as CallReviewPatientIdRouteImport } from './routes/call-review/$patientId'
import { Route as PatientsIndexRouteImport } from './routes/patients/index'
import { Route as PatientsPatientIdRouteImport } from './routes/patients/$patientId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CareAssessmentRoute = CareAssessmentRouteImport.update({
  id: '/care-assessment',
  path: '/care-assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowUpsRoute = FollowUpsRouteImport.update({
  id: '/follow-ups',
  path: '/follow-ups',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MyCareRoute = MyCareRouteImport.update({
  id: '/my-care',
  path: '/my-care',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientLoginRoute = PatientLoginRouteImport.update({
  id: '/patient-login',
  path: '/patient-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const CallReviewPatientIdRoute = CallReviewPatientIdRouteImport.update({
  id: '/call-review/$patientId',
  path: '/call-review/$patientId',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIndexRoute = PatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsPatientIdRoute = PatientsPatientIdRouteImport.update({
  id: '/patients/$patientId',
  path: '/patients/$patientId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/care-assessment': typeof CareAssessmentRoute
  '/follow-ups': typeof FollowUpsRoute
  '/login': typeof LoginRoute
  '/my-care': typeof MyCareRoute
  '/patient-login': typeof PatientLoginRoute
  '/providers': typeof ProvidersRoute
  '/call-review/$patientId': typeof CallReviewPatientIdRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/patients/': typeof PatientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/care-assessment': typeof CareAssessmentRoute
  '/follow-ups': typeof FollowUpsRoute
  '/login': typeof LoginRoute
  '/my-care': typeof MyCareRoute
  '/patient-login': typeof PatientLoginRoute
  '/providers': typeof ProvidersRoute
  '/call-review/$patientId': typeof CallReviewPatientIdRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/patients': typeof PatientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/care-assessment': typeof CareAssessmentRoute
  '/follow-ups': typeof FollowUpsRoute
  '/login': typeof LoginRoute
  '/my-care': typeof MyCareRoute
  '/patient-login': typeof PatientLoginRoute
  '/providers': typeof ProvidersRoute
  '/call-review/$patientId': typeof CallReviewPatientIdRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/patients/': typeof PatientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/care-assessment'
    | '/follow-ups'
    | '/login'
    | '/my-care'
    | '/patient-login'
    | '/providers'
    | '/call-review/$patientId'
    | '/patients/$patientId'
    | '/patients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/care-assessment'
    | '/follow-ups'
    | '/login'
    | '/my-care'
    | '/patient-login'
    | '/providers'
    | '/call-review/$patientId'
    | '/patients/$patientId'
    | '/patients'
  id:
    | '__root__'
    | '/'
    | '/care-assessment'
    | '/follow-ups'
    | '/login'
    | '/my-care'
    | '/patient-login'
    | '/providers'
    | '/call-review/$patientId'
    | '/patients/$patientId'
    | '/patients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CareAssessmentRoute: typeof CareAssessmentRoute
  FollowUpsRoute: typeof FollowUpsRoute
  LoginRoute: typeof LoginRoute
  MyCareRoute: typeof MyCareRoute
  PatientLoginRoute: typeof PatientLoginRoute
  ProvidersRoute: typeof ProvidersRoute
  CallReviewPatientIdRoute: typeof CallReviewPatientIdRoute
  PatientsPatientIdRoute: typeof PatientsPatientIdRoute
  PatientsIndexRoute: typeof PatientsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care-assessment': {
      id: '/care-assessment'
      path: '/care-assessment'
      fullPath: '/care-assessment'
      preLoaderRoute: typeof CareAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/follow-ups': {
      id: '/follow-ups'
      path: '/follow-ups'
      fullPath: '/follow-ups'
      preLoaderRoute: typeof FollowUpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-care': {
      id: '/my-care'
      path: '/my-care'
      fullPath: '/my-care'
      preLoaderRoute: typeof MyCareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient-login': {
      id: '/patient-login'
      path: '/patient-login'
      fullPath: '/patient-login'
      preLoaderRoute: typeof PatientLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call-review/$patientId': {
      id: '/call-review/$patientId'
      path: '/call-review/$patientId'
      fullPath: '/call-review/$patientId'
      preLoaderRoute: typeof CallReviewPatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/': {
      id: '/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof PatientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$patientId': {
      id: '/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof PatientsPatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CareAssessmentRoute: CareAssessmentRoute,
  FollowUpsRoute: FollowUpsRoute,
  LoginRoute: LoginRoute,
  MyCareRoute: MyCareRoute,
  PatientLoginRoute: PatientLoginRoute,
  ProvidersRoute: ProvidersRoute,
  CallReviewPatientIdRoute: CallReviewPatientIdRoute,
  PatientsPatientIdRoute: PatientsPatientIdRoute,
  PatientsIndexRoute: PatientsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
